eureka:
  client:
    service-url:
      defaultZone: http://mathengine-service-registry:8761/eureka/


spring:
  r2dbc:
    url: r2dbc:mysql://mathengine-client-db:3306/mathengineclient
    username: sa
    password: secret


#Spring boot actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # Management and tracing configuration
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
      remote-fields:
        - userId
        - calculationType
  zipkin:
    tracing:
      endpoint: http://mathengine-zipkin:9411/api/v2/spans