services:

    mathengine-service-registry:
        image: ghcr.io/cyberminddbs/mathengine-service-registry:1.0
        container_name: mathengine-service-registry
        ports:
            - "8761:8761"
        networks:
            - mathengine

    mathengine-redis:
        image: redis:7-alpine
        container_name: mathengine-redis
        ports:
            - "6379:6379"
        networks:
            - mathengine
        volumes: 
            - mathengine-redis-data:/data

    mathengine-gateway:
        image: ghcr.io/cyberminddbs/mathengine-gateway:1.0
        container_name: mathengine-gateway
        depends_on:
            - mathengine-service-registry
            - mathengine-redis
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengine-assist:
        image: ghcr.io/cyberminddbs/mathengine-assist:1.0
        container_name: mathengine-assist
        depends_on:
            - mathengine-service-registry
            - mathengine-gateway
            - mathengine-redis
        environment:
            - SERVER_PORT=8082
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengine-core:
        image: ghcr.io/cyberminddbs/mathengine-core:1.0
        depends_on:
            - mathengine-service-registry
            - mathengine-gateway
            - mathengine-assist
        environment:
            - SERVER_PORT=8084
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengine-client-db:
        image: mysql:8.1
        container_name: mathengine-client-db
        environment:
            MYSQL_DATABASE: mathengineclient
            MYSQL_USER: sa
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        networks:
            - mathengine
        volumes:
            - mathengine-client-data:/var/lib/mysql

    mathengine-client:
        image: ghcr.io/cyberminddbs/mathengine-client:1.0
        container_name: mathengine-client
        depends_on:
            - mathengine-service-registry
            - mathengine-gateway
            - mathengine-core
            - mathengine-client-db
        environment:
            - SERVER_PORT=8081
            - SPRING_PROFILES_ACTIVE=prod
        restart: unless-stopped
        networks:
            - mathengine

networks:
    mathengine:
        driver: bridge

volumes:
    mathengine-client-data:
    mathengine-redis-data:
