services:

    service-registry:
        image: ghcr.io/cyberminddbs/math-engine-prod-service-registry:1.0
        container_name: service-registry
        ports:
            - "8761:8761"
        networks:
            - mathengine

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - mathengine
        volumes: 
            - redis-data:/data

    api-gateway:
        image: ghcr.io/cyberminddbs/math-engine-prod-api-gateway:1.0
        container_name: api-gateway
        depends_on:
            - service-registry
            - redis
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengine-assist:
        image: ghcr.io/cyberminddbs/math-engine-prod-mathengine-assist:1.0
        container_name: mathengine-assist
        depends_on:
            - service-registry
            - api-gateway
            - redis
        environment:
            - SERVER_PORT=8082
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengine:
        image: ghcr.io/cyberminddbs/math-engine-prod-mathengine:1.0
        depends_on:
            - service-registry
            - api-gateway
            - mathengine-assist
        environment:
            - SERVER_PORT=8084
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - mathengine

    mathengineclient-db:
        image: mysql:8.1
        container_name: mathengineclient-db
        environment:
            MYSQL_DATABASE: mathengineclient
            MYSQL_USER: sa
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        networks:
            - mathengine
        volumes:
            - mathengineclient-data:/var/lib/mysql

    mathengine-client:
        image: ghcr.io/cyberminddbs/math-engine-prod-mathengine-client:1.0
        container_name: mathengine-client
        depends_on:
            - service-registry
            - api-gateway
            - mathengine
            - mathengineclient-db
        environment:
            - SERVER_PORT=8081
            - SPRING_PROFILES_ACTIVE=prod
        restart: unless-stopped
        networks:
            - mathengine

networks:
    mathengine:
        driver: bridge

volumes:
    mathengineclient-data:
    redis-data:
