eureka:
  client:
    service-url:
      defaultZone: http://mathengine-service-registry:8761/eureka/

spring:
  data:
    redis:
      host: mathengine-redis
      port: 6379

#Actuator settings
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://mathengine-zipkin:9411/api/v2/spans

  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include=*:
