server:
  port: 8083

spring:
  profiles:
    active: default
  application:
   name: MathEngineAdminServer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
