server:
  port: 8080

spring:
  profiles:
    active: default
  data:
    redis:
      host: localhost
      port: 6379

  application:
   name: MathEngineApiGateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: MathEngine
              uri: lb://MathEngine
              predicates:
                - Path=/api/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}" # Resolves client IP
                    redis-rate-limiter.replenishRate: 1    # token replenish per second
                    redis-rate-limiter.burstCapacity: 5    # max burst
                    redis-rate-limiter-requestedTokens: 1  # tokens per request

            - id: MathEngineAssist
              uri: lb://MathEngineAssist
              predicates:
                - Path=/assist/**

            - id: MathEngineClient
              uri: lb://MathEngineClient
              predicates:
                - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#Actuator settings for micrometer tracing:
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    redis:
      enabled: false


#Logback settings for log file location
logging:
  file:
    path: C:\MathEngineServices-logs