eureka:
  client:
    service-url:
      defaultZone: http://mathengine-service-registry:8761/eureka/

#Actuator settings for micrometer tracing:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://mathengine-zipkin:9411/api/v2/spans